#!/bin/bash

while true
do
	echo
	read -p "make " make
	read -p "model " model
	read -p "serial " serial
	read -p "year " year
	echo
	echo $make	$model $serial $year >> invantory
	clear
	cat invantory
	echo
	echo For exit simply press Ctrl+c
	sleep 3
done
